//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accesodatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using entidades;
    public partial class zapatoswebEntidades : DbContext
    {
        public zapatoswebEntidades()
            : base("name=zapatoswebEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<PedidoDet> PedidoDet { get; set; }
        public virtual DbSet<PedidoEnCab> PedidoEnCab { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tallas> Tallas { get; set; }
        public virtual DbSet<TipoZapato> TipoZapato { get; set; }
        public virtual DbSet<Zapatos> Zapatos { get; set; }
    
        public virtual int PA_Clientes_Actualizar(Nullable<int> idCliente, string nombre, string ap1, string ap2, string telefono, string email)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var ap1Parameter = ap1 != null ?
                new ObjectParameter("Ap1", ap1) :
                new ObjectParameter("Ap1", typeof(string));
    
            var ap2Parameter = ap2 != null ?
                new ObjectParameter("Ap2", ap2) :
                new ObjectParameter("Ap2", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Clientes_Actualizar", idClienteParameter, nombreParameter, ap1Parameter, ap2Parameter, telefonoParameter, emailParameter);
        }
    
        public virtual int PA_Clientes_Eliminar(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Clientes_Eliminar", idClienteParameter);
        }
    
        public virtual int PA_Clientes_insertar(string nombre, string ap1, string ap2, string telefono, string email)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var ap1Parameter = ap1 != null ?
                new ObjectParameter("Ap1", ap1) :
                new ObjectParameter("Ap1", typeof(string));
    
            var ap2Parameter = ap2 != null ?
                new ObjectParameter("Ap2", ap2) :
                new ObjectParameter("Ap2", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Clientes_insertar", nombreParameter, ap1Parameter, ap2Parameter, telefonoParameter, emailParameter);
        }
    
        public virtual ObjectResult<PA_Clientes_MostrarDetalle_Result> PA_Clientes_MostrarDetalle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Clientes_MostrarDetalle_Result>("PA_Clientes_MostrarDetalle");
        }
    
        public virtual ObjectResult<PA_Clientes_MostrarDetallexid_Result> PA_Clientes_MostrarDetallexid(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Clientes_MostrarDetallexid_Result>("PA_Clientes_MostrarDetallexid", idClienteParameter);
        }
    
        public virtual int PA_Pedidodetalle_Actualizar(Nullable<int> idPedido, Nullable<int> idZapato, Nullable<int> cantidad)
        {
            var idPedidoParameter = idPedido.HasValue ?
                new ObjectParameter("IdPedido", idPedido) :
                new ObjectParameter("IdPedido", typeof(int));
    
            var idZapatoParameter = idZapato.HasValue ?
                new ObjectParameter("IdZapato", idZapato) :
                new ObjectParameter("IdZapato", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Pedidodetalle_Actualizar", idPedidoParameter, idZapatoParameter, cantidadParameter);
        }
    
        public virtual int PA_Pedidodetalle_eliminar(Nullable<int> idPedido)
        {
            var idPedidoParameter = idPedido.HasValue ?
                new ObjectParameter("IdPedido", idPedido) :
                new ObjectParameter("IdPedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Pedidodetalle_eliminar", idPedidoParameter);
        }
    
        public virtual int PA_Pedidodetalle_insertar(Nullable<int> idpedido, Nullable<int> idZapato, Nullable<int> cantidad)
        {
            var idpedidoParameter = idpedido.HasValue ?
                new ObjectParameter("idpedido", idpedido) :
                new ObjectParameter("idpedido", typeof(int));
    
            var idZapatoParameter = idZapato.HasValue ?
                new ObjectParameter("IdZapato", idZapato) :
                new ObjectParameter("IdZapato", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Pedidodetalle_insertar", idpedidoParameter, idZapatoParameter, cantidadParameter);
        }
    
        public virtual ObjectResult<PA_Pedidodetalle_MostrarDetalle_Result> PA_Pedidodetalle_MostrarDetalle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Pedidodetalle_MostrarDetalle_Result>("PA_Pedidodetalle_MostrarDetalle");
        }
    
        public virtual ObjectResult<PA_Pedidodetalle_MostrarDetallexid_Result> PA_Pedidodetalle_MostrarDetallexid(Nullable<int> idpedido)
        {
            var idpedidoParameter = idpedido.HasValue ?
                new ObjectParameter("idpedido", idpedido) :
                new ObjectParameter("idpedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Pedidodetalle_MostrarDetallexid_Result>("PA_Pedidodetalle_MostrarDetallexid", idpedidoParameter);
        }
    
        public virtual int PA_Pedidoencabezado_actualizar(Nullable<int> idPedido, Nullable<int> idCliente, Nullable<System.DateTime> fechPedido)
        {
            var idPedidoParameter = idPedido.HasValue ?
                new ObjectParameter("IdPedido", idPedido) :
                new ObjectParameter("IdPedido", typeof(int));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            var fechPedidoParameter = fechPedido.HasValue ?
                new ObjectParameter("FechPedido", fechPedido) :
                new ObjectParameter("FechPedido", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Pedidoencabezado_actualizar", idPedidoParameter, idClienteParameter, fechPedidoParameter);
        }
    
        public virtual int PA_Pedidoencabezado_eliminar(Nullable<int> idPedido)
        {
            var idPedidoParameter = idPedido.HasValue ?
                new ObjectParameter("IdPedido", idPedido) :
                new ObjectParameter("IdPedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Pedidoencabezado_eliminar", idPedidoParameter);
        }
    
        public virtual int PA_Pedidoencabezado_insertar(Nullable<int> idCliente, Nullable<System.DateTime> fechPedido)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            var fechPedidoParameter = fechPedido.HasValue ?
                new ObjectParameter("FechPedido", fechPedido) :
                new ObjectParameter("FechPedido", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Pedidoencabezado_insertar", idClienteParameter, fechPedidoParameter);
        }
    
        public virtual ObjectResult<PA_Pedidoencabezado_MostrarDetalle_Result> PA_Pedidoencabezado_MostrarDetalle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Pedidoencabezado_MostrarDetalle_Result>("PA_Pedidoencabezado_MostrarDetalle");
        }
    
        public virtual ObjectResult<PA_Pedidoencabezado_MostrarDetallexid_Result> PA_Pedidoencabezado_MostrarDetallexid(Nullable<int> idpedido)
        {
            var idpedidoParameter = idpedido.HasValue ?
                new ObjectParameter("idpedido", idpedido) :
                new ObjectParameter("idpedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Pedidoencabezado_MostrarDetallexid_Result>("PA_Pedidoencabezado_MostrarDetallexid", idpedidoParameter);
        }
    
        public virtual int PA_Tallas_Actualizar(Nullable<int> idTalla, string dscTalla)
        {
            var idTallaParameter = idTalla.HasValue ?
                new ObjectParameter("IdTalla", idTalla) :
                new ObjectParameter("IdTalla", typeof(int));
    
            var dscTallaParameter = dscTalla != null ?
                new ObjectParameter("DscTalla", dscTalla) :
                new ObjectParameter("DscTalla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Tallas_Actualizar", idTallaParameter, dscTallaParameter);
        }
    
        public virtual int PA_Tallas_eliminar(Nullable<int> idTalla)
        {
            var idTallaParameter = idTalla.HasValue ?
                new ObjectParameter("IdTalla", idTalla) :
                new ObjectParameter("IdTalla", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Tallas_eliminar", idTallaParameter);
        }
    
        public virtual int PA_Tallas_insertar(string dscTalla)
        {
            var dscTallaParameter = dscTalla != null ?
                new ObjectParameter("DscTalla", dscTalla) :
                new ObjectParameter("DscTalla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Tallas_insertar", dscTallaParameter);
        }
    
        public virtual ObjectResult<PA_Tallas_MostrarDetalle_Result> PA_Tallas_MostrarDetalle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Tallas_MostrarDetalle_Result>("PA_Tallas_MostrarDetalle");
        }
    
        public virtual ObjectResult<PA_Tallas_MostrarDetallexid_Result> PA_Tallas_MostrarDetallexid(Nullable<int> idtalla)
        {
            var idtallaParameter = idtalla.HasValue ?
                new ObjectParameter("idtalla", idtalla) :
                new ObjectParameter("idtalla", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Tallas_MostrarDetallexid_Result>("PA_Tallas_MostrarDetallexid", idtallaParameter);
        }
    
        public virtual int PA_TipoZapato_actualizar(Nullable<int> idTipoZapato, string dscTipoZapato)
        {
            var idTipoZapatoParameter = idTipoZapato.HasValue ?
                new ObjectParameter("IdTipoZapato", idTipoZapato) :
                new ObjectParameter("IdTipoZapato", typeof(int));
    
            var dscTipoZapatoParameter = dscTipoZapato != null ?
                new ObjectParameter("DscTipoZapato", dscTipoZapato) :
                new ObjectParameter("DscTipoZapato", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_TipoZapato_actualizar", idTipoZapatoParameter, dscTipoZapatoParameter);
        }
    
        public virtual int PA_TipoZapato_eliminar(Nullable<int> idTipoZapato)
        {
            var idTipoZapatoParameter = idTipoZapato.HasValue ?
                new ObjectParameter("IdTipoZapato", idTipoZapato) :
                new ObjectParameter("IdTipoZapato", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_TipoZapato_eliminar", idTipoZapatoParameter);
        }
    
        public virtual int PA_TipoZapato_insertar(string dscTipoZapato)
        {
            var dscTipoZapatoParameter = dscTipoZapato != null ?
                new ObjectParameter("DscTipoZapato", dscTipoZapato) :
                new ObjectParameter("DscTipoZapato", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_TipoZapato_insertar", dscTipoZapatoParameter);
        }
    
        public virtual ObjectResult<PA_TipoZapato_MostrarDetalle_Result> PA_TipoZapato_MostrarDetalle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_TipoZapato_MostrarDetalle_Result>("PA_TipoZapato_MostrarDetalle");
        }
    
        public virtual ObjectResult<PA_TipoZapato_MostrarDetallexid_Result> PA_TipoZapato_MostrarDetallexid(Nullable<int> idtipozapato)
        {
            var idtipozapatoParameter = idtipozapato.HasValue ?
                new ObjectParameter("idtipozapato", idtipozapato) :
                new ObjectParameter("idtipozapato", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_TipoZapato_MostrarDetallexid_Result>("PA_TipoZapato_MostrarDetallexid", idtipozapatoParameter);
        }
    
        public virtual ObjectResult<PA_Zapato_MostrarDetalle_Result> PA_Zapato_MostrarDetalle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Zapato_MostrarDetalle_Result>("PA_Zapato_MostrarDetalle");
        }
    
        public virtual ObjectResult<PA_Zapato_MostrarDetalles_Result> PA_Zapato_MostrarDetalles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Zapato_MostrarDetalles_Result>("PA_Zapato_MostrarDetalles");
        }
    
        public virtual int PA_Zapatos_Actualizar(string dscZapato, Nullable<int> idTipoZapato, string color, Nullable<decimal> precio, Nullable<int> cantidadEistencia, Nullable<int> idTalla, Nullable<int> idZapato)
        {
            var dscZapatoParameter = dscZapato != null ?
                new ObjectParameter("DscZapato", dscZapato) :
                new ObjectParameter("DscZapato", typeof(string));
    
            var idTipoZapatoParameter = idTipoZapato.HasValue ?
                new ObjectParameter("IdTipoZapato", idTipoZapato) :
                new ObjectParameter("IdTipoZapato", typeof(int));
    
            var colorParameter = color != null ?
                new ObjectParameter("Color", color) :
                new ObjectParameter("Color", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var cantidadEistenciaParameter = cantidadEistencia.HasValue ?
                new ObjectParameter("CantidadEistencia", cantidadEistencia) :
                new ObjectParameter("CantidadEistencia", typeof(int));
    
            var idTallaParameter = idTalla.HasValue ?
                new ObjectParameter("IdTalla", idTalla) :
                new ObjectParameter("IdTalla", typeof(int));
    
            var idZapatoParameter = idZapato.HasValue ?
                new ObjectParameter("IdZapato", idZapato) :
                new ObjectParameter("IdZapato", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Zapatos_Actualizar", dscZapatoParameter, idTipoZapatoParameter, colorParameter, precioParameter, cantidadEistenciaParameter, idTallaParameter, idZapatoParameter);
        }
    
        public virtual int PA_Zapatos_eliminar(Nullable<int> idZapato)
        {
            var idZapatoParameter = idZapato.HasValue ?
                new ObjectParameter("IdZapato", idZapato) :
                new ObjectParameter("IdZapato", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Zapatos_eliminar", idZapatoParameter);
        }
    
        public virtual int PA_Zapatos_insertar(string dscZapato, string color, Nullable<decimal> precio, Nullable<int> cantidadEistencia, Nullable<int> idtipozapato, Nullable<int> idtalla)
        {
            var dscZapatoParameter = dscZapato != null ?
                new ObjectParameter("DscZapato", dscZapato) :
                new ObjectParameter("DscZapato", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("Color", color) :
                new ObjectParameter("Color", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var cantidadEistenciaParameter = cantidadEistencia.HasValue ?
                new ObjectParameter("CantidadEistencia", cantidadEistencia) :
                new ObjectParameter("CantidadEistencia", typeof(int));
    
            var idtipozapatoParameter = idtipozapato.HasValue ?
                new ObjectParameter("idtipozapato", idtipozapato) :
                new ObjectParameter("idtipozapato", typeof(int));
    
            var idtallaParameter = idtalla.HasValue ?
                new ObjectParameter("idtalla", idtalla) :
                new ObjectParameter("idtalla", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Zapatos_insertar", dscZapatoParameter, colorParameter, precioParameter, cantidadEistenciaParameter, idtipozapatoParameter, idtallaParameter);
        }
    
        public virtual ObjectResult<PA_Zapatos_MostrarDetallexid_Result> PA_Zapatos_MostrarDetallexid(Nullable<int> idZapato)
        {
            var idZapatoParameter = idZapato.HasValue ?
                new ObjectParameter("IdZapato", idZapato) :
                new ObjectParameter("IdZapato", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Zapatos_MostrarDetallexid_Result>("PA_Zapatos_MostrarDetallexid", idZapatoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
